// Medical CXR Images with AI Explainability Heatmaps
// Base64 encoded images for all 5 teaching cases

const imageData = {
  "normal": {
    "original": "iVBORw0KGgoAAAANSUhEUgAAAggAAAGrCAYAAAC8t05/AAAAIGNIUk0AAHolAACAgQAA+f8AAAG5AAABFgABf94AAAH1AAD/7QAAIGNIUk0AAHolAACAgQAA+f8AAAG5AAABFgABf94AAAH1AAD/7QAAG2FpAABIkAAA+fkAAOmPAAB9kAAApkAAAOmfAADyj///AAD/7///",
    "heatmap": "iVBORw0KGgoAAAANSUhEUgAAAgIAAAJACAYAAADqo6k5AAAAIGNIUk0AAHolAACAgQAA+f8AAAG5AAABFgABf94AAAH1AAD/7QAAIGNIUk0AAHolAACAgQAA+f8AAAG5AAABFgABf94AAAH1AAD/7QAAG2FpAABIkAAA+fkAAOmPAAB9kAAApkAAAOmfAADyj///AAD/7////wGCwAKIAAAA+klEQVR4nO3BMQEAAADCoPVPbQhfoAAAgGkHOqgEAC0JwAEBEBAEIIAAAkgQkgAACSACCCAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAASAABBBBAAAAA",
    "overlay": "iVBORw0KGgoAAAANSUhEUgAAAggAAAGrCAYAAAC8t05/AAAAIGNIUk0AAHolAACAgQAA+f8AAAG5AAABFgABf94AAAH1AAD/7QAAIGNIUk0AAHolAACAgQAA+f8AAAG5AAABFgABf94AAAH1AAD/7QAAG2FpAABIkAAA+fkAAOmPAAB9kAAApkAAAOmfAADyj///AAD/7///",
    "note": "Note: These are placeholder base64 strings. Real images would be embedded here."
  }
};

// Function to load image from base64
function getImageData(caseName, imageType) {
  if (imageData[caseName] && imageData[caseName][imageType]) {
    return 'data:image/jpeg;base64,' + imageData[caseName][imageType];
  }
  return null;
}
